export const SET_NAVS_CURRENT_ROUTER = 'SET_NAVS_CURRENT_ROUTER';
export const SET_NAVS_CURRENT_ITEMS = 'SET_NAVS_CURRENT_ITEMS';
export const SET_NAVS_CURRENT_ITEM_ACTIVE = 'SET_NAVS_CURRENT_ITEMS_ACTIVE';

export const SET_NAVS_ACTIVITY = 'SET_NAVS_ACTIVITY';

export const  SET_NAVS_CURRENT_PARENT_ROUTER = 'SET_NAVS_CURRENT_PARENT_ROUTER';
export const  SET_NAVS_CURRENT_CHILD_ROUTER = 'SET_NAVS_CURRENT_CHILD_ROUTER';

export const SET_USER_NAVS = 'SET_USER_NAVS';






